{{- if .Values.haRaft.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-ha-raft" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: ha-raft
  {{- if or .Values.haRaft.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- if or .Values.haRaft.service.annotations .Values.commonAnnotations }}
    {{- $annotations := include "common.tplvalues.merge" ( dict "values" ( list .Values.haRaft.service.annotations .Values.commonAnnotations ) "context" . ) }}
    {{- include "common.tplvalues.render" ( dict "value" $annotations "context" $) | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  type: ClusterIP
  publishNotReadyAddresses: true
  # clusterIP: None
  ports:
    - port: {{ .Values.haRaft.service.port }}
      targetPort: ha-raft
      protocol: TCP
      name: ha-raft
    {{- range until 29 }}
    - port: {{ add 4370 . }}
      targetPort: {{ printf "ha-raft-%d" . }}
      protocol: TCP
      name: {{ printf "ha-raft-%d" . }}
    {{- end }}
  selector: {{- include "common.labels.matchLabels" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: cisco-nso
{{- end }}
