image:
  pullSecrets:
    - ci-regcred

extraDeploy:
  - |
      apiVersion: v1
      kind: Secret
      metadata:
        name: {{ mustFirst .Values.image.pullSecrets }}
        namespace: {{ include "common.names.namespace" . | quote }}
        labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
          app.kubernetes.io/component: cisco-nso
        {{- if .Values.commonAnnotations }}
        annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
        {{- end }}
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: {{ printf "{\"auths\":{\"%s\":{\"username\":\"%s\",\"password\":\"%s\",\"email\":\"%s\",\"auth\":\"%s\"}}}" "ghcr.io" .Values.ciPullSecrets.username .Values.ciPullSecrets.password "" (printf "%s:%s" .Values.ciPullSecrets.username .Values.ciPullSecrets.password | b64enc) | b64enc }}

# backups:
#   enabled: true
#   cronjob:
#     annotations:
#       helm.sh/hook: pre-upgrade

# ingress:
#   enabled: true
