apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-configuration" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: cisco-nso
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- include "common.tplvalues.render" ( dict "value" (.Files.Glob "files/*.conf").AsConfig "context" $ ) | nindent 2 }}
  {{- include "common.tplvalues.render" ( dict "value" (.Files.Glob "files/*.xml").AsConfig "context" $ ) | nindent 2 }}
  {{- if .Values.extraConfig.raw }}
  99-custom-nso.conf: |-
    {{- include "common.tplvalues.render" ( dict "value" .Values.extraConfig.raw "context" $ ) | nindent 4 }}
  {{- end }}
