{{- if .Values.customPreNcsStartScripts }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-pre-ncs-start" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: cisco-nso
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.customPreNcsStartScripts }}
  {{- include "common.tplvalues.render" (dict "value" .Values.customPreNcsStartScripts "context" $) | nindent 2 }}
  {{- end }}
{{- end }}
{{- if .Values.customPostNcsStartScripts }}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-post-ncs-start" (include "common.names.fullname" .) | trunc 63 | trimSuffix "-" }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: cisco-nso
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
data:
  {{- if .Values.customPostNcsStartScripts }}
  {{- include "common.tplvalues.render" (dict "value" .Values.customPostNcsStartScripts "context" $) | nindent 2 }}
  {{- end }}
{{- end }}
