{{- if not .Values.auth.basic.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secrets.name" (dict "defaultNameSuffix" "admin-basic-auth" "context" $) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: cisco-nso
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/basic-auth
data:
  username: {{ .Values.auth.basic.username | b64enc | quote }}
  password: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.secrets.name" (dict "defaultNameSuffix" "admin-basic-auth" "context" $)) "key" "password" "providedValues" (list "auth.basic.password") "length" 16 "context" $) }}
{{- end }}
{{- if not .Values.auth.ssh.existingSecret }}
---
{{- $privateKey := coalesce .Values.auth.ssh.privateKey (genPrivateKey "rsa") }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secrets.name" (dict "defaultNameSuffix" "admin-ssh-auth" "context" $) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: cisco-nso
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: kubernetes.io/ssh-auth
data:
  ssh-privatekey: {{ include "common.secrets.lookup" (dict "secret" (include "common.secrets.name" (dict "defaultNameSuffix" "admin-ssh-auth" "context" $)) "key" "ssh-privatekey" "defaultValue" $privateKey "context" $) }}
{{- end }}
{{- if not .Values.auth.ipc.existingSecret }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "common.secrets.name" (dict "defaultNameSuffix" "ipc-token" "context" $) }}
  namespace: {{ include "common.names.namespace" . | quote }}
  labels: {{- include "common.labels.standard" ( dict "customLabels" .Values.commonLabels "context" $ ) | nindent 4 }}
    app.kubernetes.io/component: cisco-nso
  {{- if .Values.commonAnnotations }}
  annotations: {{- include "common.tplvalues.render" ( dict "value" .Values.commonAnnotations "context" $ ) | nindent 4 }}
  {{- end }}
type: Opaque
data:
  token: {{ include "common.secrets.passwords.manage" (dict "secret" (include "common.secrets.name" (dict "defaultNameSuffix" "ipc-token" "context" $)) "key" "token" "providedValues" (list "auth.ipc.token") "length" 16 "context" $) }}
{{- end }}
