apiVersion: v2
version: 7.1.11
name: cisco-nso
description: Cisco Network Services Orchestrator (NSO)
# renovate: image=ghcr.io/cisco-nso-prod
appVersion: "6.4"
type: application
keywords:
  - network
  - cisco
  - nso
  - orchestrator
home: https://www.cisco.com/go/nso
icon: https://gitlab.com/uploads/-/system/group/avatar/6082355/NSO_fc_256.png
sources:
  - https://github.com/LeoColomb/charts/tree/main/charts/cisco-nso
  - https://developer.cisco.com/docs/nso/
maintainers:
  - name: LeoColomb
    url: https://github.com/LeoColomb
kubeVersion: ^1.23.0-0
dependencies:
  - name: common
    repository: oci://registry-1.docker.io/bitnamicharts
    version: ^2.29.0
    tags:
      - bitnami-common
annotations:
  artifacthub.io/images: |
    - name: volume-permissions
      image: docker.io/bitnami/os-shell:12-debian-12-r35
    - name: status-labeler
      image: docker.io/bitnami/kubectl:1.32.0-debian-12-r0
    - name: log-rotate
      image: docker.io/imroc/logrotate:3.21.0
  artifacthub.io/license: Apache-2.0
  artifacthub.io/links: |
    - name: Upstream Documentation
      url: https://developer.cisco.com/docs/nso/
    - name: Deploying Cisco NSO on Kubernetes
      url: https://developer.cisco.com/docs/nso/deploying-cisco-nso-on-kubernetes/
  artifacthub.io/signKey: |
    fingerprint: 7D422B98DC0F24610C5807CBB9FDEEE84C92D2AA
    url: https://leocolomb.github.io/charts/gpg.pub
  artifacthub.io/changes: |
    - kind: changed
      description: New release
      links:
        - name: Changelog on GitHub Releases
          url: https://github.com/LeoColomb/charts/releases?q=cisco-nso-
